## boolean operators on numpy arrays

**numpy** -  *Data Science equivalent of Python lists*

In [1]:
import numpy as np

In [2]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [10]:
my_house > 10

array([ True,  True,  True, False])

In [11]:
my_house < 20

array([ True, False,  True,  True])

In [13]:
my_house > 10 and my_house < 20

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

- This is not as straightforward as it works on boolean values.
- We have the following 3 methods for boolean operarions on numpy arrays:
    * np.logical_and(exp1, exp2)
    * np.logical_or(exp1, exp2)
    * np.logical_not(exp1, exp2)

In [14]:
np.logical_and(my_house > 10, my_house < 20)

array([ True, False,  True, False])

In [15]:
# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False False False  True]


In [17]:
my_house[ np.logical_or(my_house>18.5, my_house < 10) ]

array([20. ,  9.5])

## Iterating 2d numpy arrays

In [24]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

meas= np.array([np_height, np_weight])
meas

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [25]:
for val in meas :
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


- A 2d array is itself made of 1d arrays
- So it iterates over 2d array, one 1d array at a time
- To iterate over the entire array, one element at a time, we use numpy function **np.nditer()**

In [27]:
for val in np.nditer(meas):
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7
